Assistant/assistant/assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notZ.urls'))
]

Assistant/assistant/notZ/urls.py
from django.urls import path

from . import views
app_name = 'notZ'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('init/', views.init_days, name='init'),
    path('schedule/', views.show_schedule, name='schedule'),
    path('<int:day_id>/', views.day_edit, name='day_edit'),
]

Assistant/assistant/notZ/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
import django.utils
import random


class MyUser(AbstractUser):
    def activate(self):
        self.activated = True

    def full_name(self):
        return self.last_name + ' ' + self.first_name+' '+self.midname


class Subject(models.Model):
    name = models.CharField(max_length=128, default='')
    hometask = models.ForeignKey(to='Hometask', null=True, on_delete=models.SET_NULL, related_name='homework')

class Day(models.Model):
    name = models.CharField(max_length=128, default='')
    schedule = models.ManyToManyField(to='Subject', related_name='schedule')
    note = models.CharField(max_length=300, default='')

    def return_schedule(self):
        res = [i for i in self.schedule.all()]
        return res


class Punkt(models.Model):
    text = models.CharField(max_length=300, default='')
    ready = models.BooleanField(default=False)


class Hometask(models.Model):
    punkts = models.ManyToManyField(to='Punkt', related_name="punkts", default='None')
    def check_completed(self):
        res = True
        for i in  self.punks.all():
            if i.ready == False:
                res = False
                break
        return res

    def return_punkts(self):
        return list([i for i in self.punkts.all()])


    def return_str(self):
        res = ''
        print(self.return_punkts())
        for i in self.return_punkts():
            if i.ready:
                res += i.text + ': ' + '<b style="color:#00c92b">Сделано</b>' + '<br>' if i.text != '' else ''
            else:
                res += i.text + ': ' + '<b style="color:#e44c4c">WIP</b>' + '<br>' if i.text != '' else ''
        return res


    def return_str_non(self):
        res = ''
        print(self.return_punkts())
        for i in self.return_punkts():
            if i.ready:
                res += i.text + '>' + '!'
            else:
                res += i.text + '<' + '!'
        return res

Assistant/assistant/notZ/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
import django.contrib.auth
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.shortcuts import render
from .models import *
from django.contrib.auth.hashers import *
import hashlib
import datetime
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseNotFound
import smtplib


def init_days(request):
    '''l = ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота']
    for i in l:
        day = Day(name=i)
        day.save()'''
    return render(request, 'index.html', dict())

@login_required(login_url='/login')
def show_schedule(request):
    context=dict()

    days = sorted([i for i in Day.objects.all()], key=lambda x: x.id)
    context['f'] = days[0].note
    context['s'] = days[1].note
    context['t'] = days[2].note
    context['fo'] = days[3].note
    context['fi'] = days[4].note
    context['si'] = days[5].note

    for i in days:
        context[str(i.name)] = [i for i in i.schedule.all()]
    return render(request, 'schedule.html', context)

def registration(request):
    context = dict()
    if request.method == 'POST':
        form = request.POST
        if form['username'] != '' and form['password1'] != '' and form['password2'] != '' and len(form['username']) > 4 and form['password1'] == form['password2']:
            user = MyUser.objects.create_user(username = form['username'], password=form['password1'])
            user.save()
            context['message'] = 'Зареган!'
            return HttpResponseRedirect("/login")
        else:
            context['message'] = 'Проверьте правильность данных!'

    context['user'] = request.user
    return render(request, 'registration.html', context)

def index(request):
    context = dict()
    context['user'] = request.user
    return render(request, 'index.html', context)

def line_to_hw(line, instance_hw):
    if instance_hw is not None:
        line = line[:len(line) - 1].split('!')
        print(line)
        for i in [j for j in instance_hw.punkts.all()]:
            instance_hw.punkts.remove(i)
            instance_hw.save()
        for i in line:
            print(i)
            if len(i) > 0:
                if i[-1] == '>':
                    punkt = Punkt(text= i[:len(i)-1] if len(i) > 1 else '', ready=True)
                else:
                    punkt = Punkt(text=i[:len(i) - 1] if len(i) > 1 else '', ready=False)
            else:
                punkt =Punkt(text = '', ready=False)
            punkt.save()
            instance_hw.punkts.add(punkt)
            instance_hw.save()

@login_required(login_url='/login')
def day_edit(request, day_id):
    context = dict()
    day = Day.objects.filter(id = day_id)[0]
    context['day'] = Day.objects.filter(id = day_id)[0]
    context['day_name'] = Day.objects.filter(id = day_id)[0].name
    context['subs'] = Day.objects.filter(id = day_id)[0].return_schedule()
    context['subjects'] = [i for i in Subject.objects.filter()]
    if request.method == 'POST':
        for i in Subject.objects.filter():
            if 'del_' + str(i.id) in request.POST:
                if i in day.schedule.all():
                    day.schedule.remove(i)
                    day.save()
                    return HttpResponseRedirect('/' + str(day_id))
        form = request.POST
        if 'Change' in form:
            subjs = [i for i in Subject.objects.filter()]
            day = Day.objects.filter(id=day_id)[0]
            for i in [j for j in day.schedule.all()]:
                day.schedule.remove(i)
                day.save()
            for i in subjs:
                res = []
                if str(i.id) in form:
                    day.schedule.add(Subject.objects.filter(name = form[str(i.id)])[0])
                    day.save()


            all_homeworks = [i for i in Hometask.objects.filter()]
            for i in subjs:
                if 'hw_' + str(i.id) in form:
                    print(form['hw_' + str(i.id)])
                    t = i.hometask
                    if t is not None:
                        line_to_hw(form['hw_' + str(i.id)], t)
                    else:
                        temp = Hometask(id = random.randint(100, 9999999))
                        temp.save()
                        i.hometask = temp
                        i.save()
                        t = i.hometask
                        line_to_hw(form['hw_' + str(i.id)], t)

            day.note = form['notaa']
            day.save()
            return HttpResponseRedirect('/' + str(day_id))
        elif 'Add' in form:
            Day.objects.filter(id=day_id)[0].schedule.add(Subject.objects.filter(name = form['additional'])[0])
            Day.objects.filter(id=day_id)[0].save()
            return HttpResponseRedirect('/'+str(day_id))
    return render(request, 'day_edit.html', context)




def login(request):
    context = dict()
    context['user'] = request.user
    if request.method == 'POST':
        form = request.POST
        if not MyUser.objects.filter(username=form['username']):
            context['message'] = 'Нет такого пользователя!'
        else:
            user = authenticate(request, username=form['username'], password=form['password'])
            if user is not None:
                django.contrib.auth.login(request, user)
                context['message'] = 'Вход выполнен!'
                return HttpResponseRedirect('/')
            else:
                context['message'] = 'Не получилось войти:('
    return render(request, 'login.html', context)




def profile(request):
    context = dict()
    context['user'] = request.user
    if request.method == 'POST':
        if 'logout' in request.POST:
            logout(request)
            return redirect('/login')
    return render(request, 'profile.html', context)

Assistant/assistant/notZ/templates/day_edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Расписание</title>
    {% include "includes/head_includes.html"%}

    <style>
        .th-width{
            width: 50%;
        }

    </style>
</head>

<body>

<header>
    {% include "includes/navbar.html"%}
</header>

<div class="wrapper">
    <div class="container">
        <div class="form-title">
            <hr>
            <h1>{{day_name}}</h1>
            <hr>
        </div>
        <form method="POST">
            {%csrf_token%}
        <table class="table table-striped">

            <thead class="thead-dark">
            <tr>
                <th class="th-width">Урок</th>
                <th class="th-width">Задание</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {%for subj in subs%}
            <tr>
                <td>
                    <div class="form-group">
                    <input type="text" class="form-control" value="{{subj.name}}" name="{{subj.id}}" list="gr">
                    <datalist id='gr'>
                        {%for i in subjects%}
                        <option value="{{i.name}}"></option>
                        {% endfor %}
                    </datalist>
                    </div>
                </td>
                <td>
                    <div class="form-group">
                    <input type="text" class="form-control" value="{{subj.hometask.return_str_non}}" name="hw_{{subj.id}}">
                    </div>
                </td>
                <td><input type="submit" value="Удалить" name='del_{{subj.id}}' class="btn btn-danger"></td>
            </tr>
            {%endfor%}

            </tbody>
        </table>
            <p> Новый предмет</p>
            <input type="text" class="form-control" value="" name="additional" list="gr1">
                    <datalist id='gr1'>
                        {%for i in subjects%}
                        <option value="{{i.name}}"></option>
                        {% endfor %}
                    </datalist>
            <br>
            <p>Заметка</p>
            <input type='text' value="{{day.note}}" placeholder="Заметка" name='notaa' class="form-control">
            <br>
            <input type="submit" value="Добавить" name='Add' class="btn btn-dark mr-sm-2">

            <input type="submit" value="Изменить" name='Change' class="btn btn-dark mr-sm-2">
        </form>
    </div>
</div>
</body>

</html>

Assistant/assistant/notZ/templates/includes/head_includes.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
    integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
</script>

Assistant/assistant/notZ/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">notZ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">

            <ul class="navbar-nav mr-auto">

                {% if user %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'notZ:schedule' %}">Мое расписание</a>
                </li>
                {% endif %}
                
            </ul>
            <form class="form-inline my-2 my-lg-0">
                {% if not user.is_authenticated %}
                <a class="btn btn-outline-dark mr-sm-2" href="{% url 'notZ:login' %}">Вход</a>
                <a class="btn btn-dark mr-sm-2" href="{% url 'notZ:registration' %}">Регистрация</a>
                {% else %}
                <a class="btn btn-outline-primary mr-sm-2"  href="{% url 'notZ:profile' %}"> {{ user.username }} </a>
                {% endif %}
            </form>
        </div>

    </div>
</nav>

Assistant/assistant/notZ/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include "includes/head_includes.html"%}
</head>
<body>
<header>
    {% include "includes/navbar.html"%}
</header>
 <div class="wrapper">
    <div class="container">
        <br>
        <br>
        <br><br>
        <h1>ПОЧЕМУ НИЧЕГО НЕ РАБОТАЕТ ЫАЫВАЫВ</h1>
    </div>
 </div>

</body>
</html>

Assistant/assistant/notZ/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Вход</title>
    {% include "includes/head_includes.html"%}
</head>

<body>
    
    <header>
        {% include "includes/navbar.html"%}
    </header>

    <div class="wrapper">
    <div class="container">
        <div class="form-title">
            <hr>
            <h1>Вход</h1>
            <hr>
            <p>Войдите, чтобы просматривать все страницы сайта</p>
        </div>

        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label>Логин:</label>
                <input type="text" class="form-control" placeholder="Логин" name="username">
            </div>
            <div class="form-group">
                <label>Пароль:</label>
                <input type="password" class="form-control" placeholder="Пароль" name="password">
            </div>
            <input type="submit" value="Войти" name='enter' class="btn btn-dark mr-sm-2">
            <br>
            <p color="red">{{ message }}</p>
        </form>
        <div class="form-title"><p>Или <a href="/registration">активировать аккаунт</a></p></div>
    </div>
    </div>
</body>
</html>

Assistant/assistant/notZ/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Профиль</title>
    {% include "includes/head_includes.html"%}
    <style>
        .user-section{
            margin-top: 50px;
        }
        .userdata{
            /*border: solid 1px black;
            padding: 3px 0;*/
            font-size: 1.1em;
            display: flex;
            
        }
        .userparam{
            display: inline-block;
            width: 40%;
        }
        .userparam-data{
            display: inline-block;
            width: 40%;
        }
    </style>
    {% include "includes/head_includes.html"%}
</head>

<body>
    
    <header>
        {% include "includes/navbar.html"%}
    </header>

    <div class="wrapper">
    <div class="container">
        <div class="form-title">
            <hr>
            <h1>Мой профиль</h1>
            <hr>
        </div>

    <section class="user-section">
        <div class="userdata"><div class="userparam">Логин: </div>          <div class="userparam-data">{{user.username}}</div> </div>
        <hr >
        <div class="userdata"><div class="userparam">Дата регистрации: </div>            <div class="userparam-data"> {{user.date_joined}}</div></div>
        <hr>
        <hr>
        <form method="POST">
            {% csrf_token %}
        <input type="submit" value="Выйти" name='logout' class="btn-danger btn btn-form">
        </form>
    </section>

    </div>
    </div>
</body>
</html>

Assistant/assistant/notZ/templates/registration.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <title>Регистрация</title>
    {% include "includes/head_includes.html"%}
</head>

<body>

    <header>
        {% include "includes/navbar.html"%}
    </header>

    <div class="wrapper">
        <div class="container">
            <div class="form-title">
                <hr>
                <h1>Регистрация</h1>
                <hr>
            </div>

            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label>Придумайте логин:</label>
                    <input type="text" class="form-control" placeholder="Логин" name="username">
                </div>
                <div class="form-group">
                    <label>Придумайте пароль:</label>
                    <input type="password" class="form-control" placeholder="Пароль" name="password1">
                </div>
                <div class="form-group">
                    <label>Пароль:</label>
                    <input type="password" class="form-control" placeholder="Проверка пароля" name="password2">
                </div>


                <input type="submit" value="Зарегистрироваться" class="btn btn-dark mr-sm-2">
                <br>
                <p color="red">{{ message }}</p>
            </form>



        </div>
</body>

</html>

Assistant/assistant/notZ/templates/schedule.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Расписание</title>
    {% include "includes/head_includes.html"%}

    <style>
        .th-width{
            width: 50%;
        }

    </style>
</head>

<body>

<header>
    {% include "includes/navbar.html"%}
</header>

<div class="wrapper">
    <div class="container">
        <div class="form-title">
            <hr>
            <h1>Мое расписание</h1>
            <hr>
        </div>
        <div class="form-group">
            <h3>Понедельник</h3>
        </div>
        <a class="btn btn-dark mr-sm-2" style="color:white" name="monday" href="/1">Редактировать</a>
        <br>
        <br>
        <table class="table">

            <thead class="thead-dark">
            <tr>
                <th class="th-width">Урок</th>
                <th class="th-width">Задание</th>
            </tr>
            </thead>
            <tbody>
            {%for i in Понедельник%}
            <tr>
                <td>{{i.name}}</td>
                <td>{% autoescape off %}{{i.hometask.return_str}}{% endautoescape %}</td>
            </tr>
            {%endfor%}
            </tbody>

        </table>
        <div style="background-color:#f2f2f2;height:50px; padding:10px">
                    <h5 style="background-color:#f2f2f2; color: #292929">{{f}}</h5>
        </div>
        <hr>
<br>
        <br>
        <div class="form-group">
            <h3>Вторник</h3>
        </div>
        <a class="btn btn-dark mr-sm-2" style="color:white" name="tuesday"  href="/2">Редактировать</a>
        <br>
        <br>
        <table class="table">

            <thead class="thead-dark">
            <tr>
                <th class="th-width">Урок</th>
                <th class="th-width">Задание</th>
            </tr>
            </thead>
            <tbody>
            {%for i in Вторник%}
            <tr>
                <td>{{i.name}}</td>
                <td>{% autoescape off %}{{i.hometask.return_str}}{% endautoescape %}</td>
            </tr>
            {%endfor%}
            </tbody>

        </table>
        <div style="background-color:#f2f2f2;height:50px; padding:10px">
        <h5 style="background-color:#f2f2f2; color: #292929">{{s}}</h5>
        </div>
<hr><br>
        <br>
        <div class="form-group">
            <h3>Среда</h3>
        </div>
        <a class="btn btn-dark mr-sm-2" style="color:white" name="wednesday"  href="/3">Редактировать</a>
        <br>
        <br>
        <table class="table">

            <thead class="thead-dark">
            <tr>
                <th class="th-width">Урок</th>
                <th class="th-width">Задание</th>
            </tr>
            </thead>
            <tbody>
            {%for i in Среда%}
            <tr>
                <td>{{i.name}}</td>
                <td>{% autoescape off %}{{i.hometask.return_str}}{% endautoescape %}</td>
            </tr>
            {%endfor%}
            </tbody>
        </table>
        <div style="background-color:#f2f2f2;height:50px; padding:10px">
        <h5 style="background-color:#f2f2f2; color: #292929">{{t}}</h5>
        </div>
<hr><br>
        <br>
        <div class="form-group">
            <h3>Четверг</h3>
        </div>
        <a class="btn btn-dark mr-sm-2" style="color:white" name="thursday" href="/4">Редактировать</a>
        <br>
        <br>
        <table class="table">

            <thead class="thead-dark">
            <tr>
                <th class="th-width">Урок</th>
                <th class="th-width">Задание</th>
            </tr>
            </thead>
            <tbody>
            {%for i in Четверг%}
            <tr>
                <td>{{i.name}}</td>
                <td>{% autoescape off %}{{i.hometask.return_str}}{% endautoescape %}</td>
            </tr>
            {%endfor%}
            </tbody>
        </table>
        <div style="background-color:#f2f2f2;height:50px; padding:10px">
        <h5 style="background-color:#f2f2f2; color: #292929">{{fo}}</h5>
        </div>
<hr><br>
        <br>
        <div class="form-group">
            <h3>Пятница</h3>
        </div>
        <a class="btn btn-dark mr-sm-2" style="color:white" name="friday"  href="/5">Редактировать</a>
        <br>
        <br>
        <table class="table">

            <thead class="thead-dark">
            <tr>
                <th class="th-width">Урок</th>
                <th class="th-width">Задание</th>
            </tr>
            </thead>
            <tbody>
            {%for i in Пятница%}
            <tr>
                <td>{{i.name}}</td>
                <td>{% autoescape off %}{{i.hometask.return_str}}{% endautoescape %}</td>
            </tr>
            {%endfor%}
            </tbody>

        </table>

        <br>
        <div style="background-color:#f2f2f2;height:50px; padding:10px">
            <h5 style="background-color:#f2f2f2; color: #292929">{{fi}}</h5>
        </div>
        <hr>
        <br>
        <div class="form-group">
            <h3>Суббота</h3>
        </div>
        <a class="btn btn-dark mr-sm-2" style="color:white" name="saturday" href="/6">Редактировать</a>
        <br>
        <br>
        <table class="table">

            <thead class="thead-dark">
            <tr>
                <th class="th-width">Урок</th>
                <th class="th-width">Задание</th>
            </tr>
            </thead>
            <tbody>
            {%for i in Суббота%}
            <tr>
                <td>{{i.name}}</td>
                <td>{% autoescape off %}{{i.hometask.return_str}}{% endautoescape %}</td>
            </tr>
            {%endfor%}
            </tbody>
        </table>
        <div style="background-color:#f2f2f2;height:50px; padding:10px">
        <h5 style="background-color:#f2f2f2; color: #292929">{{si}}</h5>
        </div>
    </div>
</div>
</body>

</html>